sudo: false

language: node_js

node_js: 
  - "stable"

services:
  - postgresql

notifications:
  email: false

install:
  - npm install

before_script:
  - yarn global add nyc
  - psql -c 'create database me_test;' -U postgres

script:
 - npm run coveralls
 - npm run coverage